import assert from 'node:assert/strict';
import { createServer } from 'vite';
const values = new Map();
globalThis.localStorage = { getItem: key => values.get(key) || null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) };
const server = await createServer({ server: { middlewareMode: true }, appType: 'custom' });
let checks = 0;
const check = (condition, message) => { assert.ok(condition, message); checks++; };
try {
  const { demoRequest: request } = await server.ssrLoadModule('/src/api/demoClient.ts');
  const mutation = (method, body) => ({ method, body: JSON.stringify(body) });
  const cameras = await request('/cameras');
  check(cameras.length === 15, 'fifteen cameras');
  const result = await request('/vehicles/search?plate=GJ01AB1234');
  check(result.total === 5, 'known plate returns five sightings');
  check((await request('/vehicles/search?plate=ZZ99ZZ9999')).total === 0, 'unknown plate does not fabricate sightings');
  check((await request('/vehicles/search?plate=GJ01AB1234&vehicle_class=truck')).total === 0, 'class filter');
  check((await request('/vehicles/search?from=2030-01-01')).total === 0, 'date filter');
  const journey = await request('/vehicles/journey/GJ01AB1234');
  check(journey.stops.length === 5 && journey.path_coordinates.length === 5, 'journey coordinates match sightings');
  check(journey.stops.every((s,i,a) => !i || Date.parse(s.timestamp) >= Date.parse(a[i-1].timestamp)), 'journey chronological');
  const added = await request('/watchlist', mutation('POST', { plate_text: 'gj 01 xx 9999', reason: 'Test', priority: 'low' }));
  check(added.plate_text === 'GJ01XX9999', 'plate normalization');
  check((await request('/watchlist')).some(w => w.id === added.id), 'watchlist persists');
  await assert.rejects(request('/watchlist', mutation('POST', { plate_text: 'GJ01XX9999' }))); checks++;
  await request('/watchlist/' + added.id, mutation('PATCH', { active: false }));
  check(!(await request('/watchlist?active_only=true')).some(w => w.id === added.id), 'active filter');
  await request('/watchlist/' + added.id, { method: 'DELETE' });
  check(!(await request('/watchlist')).some(w => w.id === added.id), 'delete sample watchlist entry');
  const alerts = await request('/alerts?status=active');
  await request('/alerts/' + alerts[0].id + '/acknowledge', mutation('PATCH', {}));
  check((await request('/alerts?status=active')).length === alerts.length-1, 'acknowledgment persists');
  check((await request('/analytics/summary')).active_alerts === alerts.length-1, 'summary consistent');
  const evidence = await request('/evidence/preserve', mutation('POST', { sighting_id: result.items[0].id }));
  check((await request('/evidence')).length === 1, 'evidence persists in vault');
  check(evidence.metadata_hash.length === 64, 'real metadata SHA256');
  check((await request('/evidence/' + evidence.id + '/verify')).valid, 'metadata integrity verification');
  const state = JSON.parse(values.get('sentrax-demo-v1'));
  state.evidence[0].metadata_json += 'tampered'; values.set('sentrax-demo-v1', JSON.stringify(state));
  check(!(await request('/evidence/' + evidence.id + '/verify')).valid, 'tampering detected');
  const blob = await request('/evidence/' + evidence.id + '/export', { method: 'POST' });
  const bytes = new Uint8Array(await blob.arrayBuffer());
  check(bytes[0]===80 && bytes[1]===75 && bytes[2]===3 && bytes[3]===4, 'real ZIP archive header');
  check(new TextDecoder().decode(bytes).includes('Metadata-only demonstration'), 'export labels limitations');
  check((await request('/copilot/analyze', mutation('POST',{plate_text:'GJ01AB1234'}))).provider.includes('not AI'), 'summary honest provenance');
  await assert.rejects(request('/unknown-integration')); checks++;
  console.log(`${checks} demo checks passed.`);
} finally { await server.close(); }
