import React, { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { PageHeader } from '../components/layout/PageHeader';
import { Input } from '../components/ui/Input';
import { Select } from '../components/ui/Select';
import { Badge } from '../components/ui/Badge';
import { LicensePlate } from '../components/ui/LicensePlate';
import { AlertDrawer } from '../components/alerts/AlertDrawer';
import { alertsApi } from '../api/alerts';
import { evidenceApi } from '../api/evidence';
import { Alert } from '../types';
import { formatTimestamp } from '../utils/format';
import { ShieldAlert, Search, Filter, CheckCircle, Eye } from 'lucide-react';
import { toast } from 'sonner';

export const AlertsPage: React.FC = () => {
  const queryClient = useQueryClient();
  const [statusFilter, setStatusFilter] = useState('');
  const [priorityFilter, setPriorityFilter] = useState('');
  const [plateFilter, setPlateFilter] = useState('');
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);

  const { data: alerts = [], isLoading } = useQuery({
    queryKey: ['alerts', statusFilter, priorityFilter, plateFilter],
    queryFn: () =>
      alertsApi.list({
        status: statusFilter || undefined,
        priority: priorityFilter || undefined,
        plate: plateFilter || undefined,
        limit: 100,
      }),
    refetchInterval: 10000,
  });

  const handleAcknowledge = async (alert: Alert) => {
    try {
      await alertsApi.acknowledge(alert.id);
      queryClient.invalidateQueries({ queryKey: ['alerts'] });
      toast.success(`Alert for ${alert.plate_text} acknowledged.`);
      if (selectedAlert?.id === alert.id) setSelectedAlert(null);
    } catch {
      toast.error('Failed to acknowledge alert');
    }
  };

  const handleDismiss = async (alert: Alert) => {
    try {
      await alertsApi.dismiss(alert.id);
      queryClient.invalidateQueries({ queryKey: ['alerts'] });
      toast.info(`Alert for ${alert.plate_text} dismissed.`);
      if (selectedAlert?.id === alert.id) setSelectedAlert(null);
    } catch {
      toast.error('Failed to dismiss alert');
    }
  };

  const handlePreserve = async (alert: Alert) => {
    if (!alert.sighting_id) return;
    try {
      await evidenceApi.preserve(alert.sighting_id, alert.id, `CASE-ALERT-${alert.plate_text}`);
      toast.success(`Evidence preserved with SHA-256 seal for plate ${alert.plate_text}.`);
    } catch {
      toast.error('Evidence preservation failed');
    }
  };

  return (
    <div className="space-y-4">
      <PageHeader
        title="Live Surveillance Watchlist Alerts"
        description="Active and historical alerts generated by automated plate recognition cross-referencing."
      />

      {/* Filter Ribbon */}
      <div className="p-3 bg-[#0D1520] border border-[#1C2E42] rounded-[6px] grid grid-cols-1 sm:grid-cols-12 gap-3 items-center shadow-[0_1px_3px_rgba(0,0,0,0.5)]">
        <div className="sm:col-span-5">
          <Input
            placeholder="Search alerts by plate number..."
            value={plateFilter}
            onChange={(e) => setPlateFilter(e.target.value.toUpperCase())}
            icon={<Search className="w-4 h-4" />}
            className="font-mono uppercase"
          />
        </div>
        <div className="sm:col-span-4">
          <Select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            options={[
              { label: 'All Alert Statuses', value: '' },
              { label: 'Active Alerts Only', value: 'active' },
              { label: 'Acknowledged', value: 'acknowledged' },
              { label: 'Dismissed', value: 'dismissed' },
            ]}
          />
        </div>
        <div className="sm:col-span-3">
          <Select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
            options={[
              { label: 'All Priorities', value: '' },
              { label: 'Critical Priority', value: 'critical' },
              { label: 'High Priority', value: 'high' },
              { label: 'Medium Priority', value: 'medium' },
            ]}
          />
        </div>
      </div>

      {/* Alerts Table */}
      <div className="bg-[#0D1520] border border-[#1C2E42] rounded-[6px] overflow-hidden shadow-[0_1px_3px_rgba(0,0,0,0.5)]">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-[#121E2E] text-[#8FA8C0] text-[11px] font-mono border-b border-[#1C2E42] uppercase">
              <tr>
                <th className="py-2.5 px-4 font-medium">Priority</th>
                <th className="py-2.5 px-3 font-medium">Target Plate</th>
                <th className="py-2.5 px-4 font-medium">Camera Location</th>
                <th className="py-2.5 px-4 font-medium">Detection Time</th>
                <th className="py-2.5 px-4 font-medium">Watchlist Reason</th>
                <th className="py-2.5 px-3 font-medium">Status</th>
                <th className="py-2.5 px-3 text-right font-medium">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1C2E42]">
              {isLoading ? (
                <tr>
                  <td colSpan={7} className="text-center py-12 text-[#8FA8C0]">
                    Loading real-time alert logs...
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan={7} className="text-center py-16 text-[#8FA8C0]">
                    <div className="flex flex-col items-center justify-center">
                      <CheckCircle className="w-8 h-8 text-[#00C875] mb-2" />
                      <div className="text-sm font-semibold text-white">All clear</div>
                      <div className="text-xs text-[#8FA8C0] mt-1">
                        No active watchlist alerts. The system is monitoring all registered cameras.
                      </div>
                    </div>
                  </td>
                </tr>
              ) : (
                alerts.map((a) => (
                  <tr
                    key={a.id}
                    onClick={() => setSelectedAlert(a)}
                    className="hover:bg-[#121E2E] cursor-pointer transition-colors"
                  >
                    <td className="py-3 px-4">
                      <Badge
                        variant={
                          a.priority === 'critical'
                            ? 'alert'
                            : a.priority === 'high'
                            ? 'warn'
                            : 'info'
                        }
                      >
                        {a.priority}
                      </Badge>
                    </td>
                    <td className="py-3 px-3">
                      <LicensePlate plate={a.plate_text} size="sm" />
                    </td>
                    <td className="py-3 px-4">
                      <div className="font-semibold text-white">{a.camera_name || 'CAM'}</div>
                      <div className="text-[10px] text-[#8FA8C0]">{a.location_name}</div>
                    </td>
                    <td className="py-3 px-4 font-mono text-[11px] text-[#E8EFF7]">
                      {formatTimestamp(a.triggered_at)}
                    </td>
                    <td className="py-3 px-4 text-[#8FA8C0] max-w-[260px] truncate" title={a.watchlist_reason}>
                      {a.watchlist_reason || 'Flagged Target'}
                    </td>
                    <td className="py-3 px-3">
                      <span
                        className={`text-[10px] font-mono font-bold uppercase ${
                          a.status === 'active' ? 'text-[#FF3B3B]' : 'text-[#00C875]'
                        }`}
                      >
                        {a.status}
                      </span>
                    </td>
                    <td className="py-3 px-3 text-right space-x-1">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setSelectedAlert(a);
                        }}
                        className="p-1.5 text-[#8FA8C0] hover:text-[#0E7FE0] hover:bg-[#121E2E] rounded"
                        title="View Alert Details"
                      >
                        <Eye className="w-3.5 h-3.5" />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      <AlertDrawer
        alert={selectedAlert}
        onClose={() => setSelectedAlert(null)}
        onAcknowledge={handleAcknowledge}
        onDismiss={handleDismiss}
        onPreserveEvidence={handlePreserve}
      />
    </div>
  );
};
